### ISSUE TITLE
Stuck after launching visdom server

### ISSUE THREAD

**Issue by spha-code** [ThibaultGROUEIX/AtlasNet#30]
I run the demo succesfully but after I launch the visdom server

python -m visdom.server -p 8888

I am stuck, I can't write any command anymore in my anaconda window. How do I continue? thanks!

**Comment by ThibaultGROUEIX** [comment]
Hi @spha-code 
Just keep in running and open a new one,
Best regards,
Thibault

**Comment by spha-code** [comment]
Hi @ThibaultGROUEIX,

many thanks for the response. Appreciated. It took me a while because I was downloading the data. It seems to work now but I get this error when I run ./training/train_AE_AtlasNet.py . Any idea? Is this happening because I am on Windows 10?  Thank you in advance.

================BEGINNING
(atlasnet) C:\Users\user\Documents\Tensorflow\AtlasNet>python ./training/train_AE_AtlasNet.py
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Setting up a new session...
Traceback (most recent call last):
  File "./training/train_AE_AtlasNet.py", line 75, in <module>
    os.mkdir(dir_name)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'log\\2019-10-05T19:47:47.889854'

(atlasnet) C:\Users\user\Documents\Tensorflow\AtlasNet>
================END
Btw, please ignore previous versions of this edited comment

**Comment by spha-code** [comment]
Since I am in Windows 10, I replaced this line :
**dir_name =  os.path.join('log', save_path)**
with this one
**dir_name =  os.path.join('log', save_path).replace(":","_")**
and it worked!

**Comment by spha-code** [comment]
But I get this error now below when I run  ./training/train_AE_AtlasNet.py: Any idea?
Again I read it has to do with running the code in Windows...

```
(atlasnet) C:\Users\user\Documents\Tensorflow\AtlasNet>python ./training/train_AE_AtlasNet.py
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Setting up a new session...
Random Seed:  4078
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
training set 31747
testing set 7943
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Setting up a new session...
Random Seed:  8078
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
training set 31747
testing set 7943
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Documents\Tensorflow\AtlasNet\training\train_AE_AtlasNet.py", line 142, in <module>
    for i, data in enumerate(dataloader, 0):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
  File "./training/train_AE_AtlasNet.py", line 142, in <module>
    return _MultiProcessingDataLoaderIter(self)
    for i, data in enumerate(dataloader, 0):
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    w.start()
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\process.py", line 112, in start
    return _MultiProcessingDataLoaderIter(self)
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 223, in _Popen
    w.start()
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\process.py", line 112, in start
    return _default_context.get_context().Process._Popen(process_obj)
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 223, in _Popen
    return Popen(process_obj)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\reduction.py", line 60, in dump
    _check_not_importing_main()
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

(atlasnet) C:\Users\user\Documents\Tensorflow\AtlasNet>python ./training/train_AE_AtlasNet.py
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Setting up a new session...
Random Seed:  1922
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
training set 31747
testing set 7943
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Setting up a new session...
Random Seed:  8832
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
training set 31747
testing set 7943
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\runpy.py", line 263, in run_path
Traceback (most recent call last):
    pkg_name=pkg_name, script_name=fname)
  File "./training/train_AE_AtlasNet.py", line 142, in <module>
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\runpy.py", line 96, in _run_module_code
    for i, data in enumerate(dataloader, 0):
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\runpy.py", line 85, in _run_code
    return _MultiProcessingDataLoaderIter(self)
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
  File "C:\Users\user\Documents\Tensorflow\AtlasNet\training\train_AE_AtlasNet.py", line 142, in <module>
    w.start()
    for i, data in enumerate(dataloader, 0):
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\process.py", line 112, in start
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 223, in _Popen
    return _MultiProcessingDataLoaderIter(self)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 322, in _Popen
    w.start()
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\process.py", line 112, in start
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    self._popen = self._Popen(self)
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\reduction.py", line 60, in dump
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 223, in _Popen
    ForkingPickler(file, protocol).dump(obj)
    return _default_context.get_context().Process._Popen(process_obj)
BrokenPipeError: [Errno 32] Broken pipe
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\user\AppData\Local\conda\conda\envs\atlasnet\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

(atlasnet) C:\Users\user\Documents\Tensorflow\AtlasNet>
```

**Comment by ThibaultGROUEIX** [comment]
Dear @spha-code ,
Sorry i don't have pytorch experience in Windows. Let me know if you solve this. Good luck !
--Thibault

**Comment by spha-code** [comment]
Dear @ThibaultGROUEIX many thanks for your response! I quit trying on Windows and switched to Ubuntu. It worked there. But I was very often getting "cuda out of memory" error messages (even after decreasing batchSize ). It worked after I was rebooting and running python ./training/train_AE_AtlasNet.py first thing. 

It would be great if you could post at some point a simple guide(for dummies) how the code could work with a new image for svr, or is it already posted somewhere? thanks for the help so far.

**Comment by ThibaultGROUEIX** [comment]
What about this issue ? https://github.com/ThibaultGROUEIX/AtlasNet/issues/29 What are you missing?

**Comment by spha-code** [comment]
Thanks! Does this mean that if I substitute the plane image of the demo I should get results?Is this it? I tried exactly this with a camera image(without bgr) from shapenet which I decreased in dimensions to 137x137.png but the result was weird similar to the link above...

**Comment by ThibaultGROUEIX** [comment]
You should make sure that the background is all black (pixel with excatly 0 values). The right way to call the demo is `python inference/demo.py --input YOUR_IMAGE`

**Comment by spha-code** [comment]
many thanks for the respond! sounds great, I will give it a try the next few days.. (I had to delete the data for now to make space...) - the shapenet image I used had obviously white background...
