### ISSUE TITLE
A bug on running code

### ISSUE THREAD

**Issue by Yuzuki-N** [ThibaultGROUEIX/AtlasNet#70]
When i run
`python ./training/train_AE_AtlasNet.py --env $env --nb_primitives $nb_primitives |& tee ${env}.txt`.

THe program print like this:
```
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Random Seed:  6777
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 0 0.0 %
category  02828884 files 0 0.0 %
category  02933112 files 0 0.0 %
category  02958343 files 0 0.0 %
category  03001627 files 0 0.0 %
category  03211117 files 0 0.0 %
category  03636649 files 0 0.0 %
category  03691459 files 0 0.0 %
category  04090263 files 0 0.0 %
category  04256520 files 0 0.0 %
category  04379243 files 0 0.0 %
category  04401088 files 0 0.0 %
category  04530566 files 0 0.0 %
Traceback (most recent call last):
  File "./training/train_AE_AtlasNet.py", line 93, in <module>
    shuffle=True, num_workers=int(opt.workers))
  File "/home/hznu/anaconda3/envs/a2.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/home/hznu/anaconda3/envs/a2.2/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

```

**Comment by ThibaultGROUEIX** [comment]
Hi @Yuzuki-N 

The data is most likely in the wrong place. It says that it was able to load 0% of the models,

Best regards
