### ISSUE TITLE
Question about running

### ISSUE THREAD

**Issue by tang-y-q** [ThibaultGROUEIX/AtlasNet#84]
Hi，i'm soory to bother you again.
When I ran the code as you explained, I got the following error：
sh: 1: tmux: not found
Setting up a new session...
Exception in user code:

could you give me some advice？
The overall operation results in the terminal are as follows:

/home/yukon/anaconda3/envs/pymesh/bin/python "/media/yukon/Extreme SSD/AtlasNet-master/train.py"
anshu: Namespace(SVR=False, activation='relu', anisotropic_scaling=False, batch_size=32, batch_size_test=32, bottleneck_size=1024, class_choice=['airplane'], data_augmentation_axis_rotation=False, data_augmentation_random_flips=False, demo=True, demo_input_path='./doc/pictures/plane_input_demo.png', dir_name='', env='Atlasnet', hidden_neurons=512, http_port=8891, id='0', loop_per_epoch=1, lr_decay_1=120, lr_decay_2=140, lr_decay_3=145, lrate=0.001, multi_gpu=[0], nb_primitives=1, nepoch=150, no_learning=False, no_metro=False, normalization='UnitBall', num_layers=2, number_points=2500, number_points_eval=2500, random_rotation=False, random_seed=False, random_translation=False, reload_decoder_path='', reload_model_path='', remove_all_batchNorms=False, run_single_eval=False, sample=True, shapenet13=False, start_epoch=0, template_type='SPHERE', train_only_encoder=False, visdom_port=8890, workers=0)
Loaded compiled 3D CUDA chamfer distance
Launching new visdom instance in port 8890
TMUX=0 tmux new-session -d -s visdom_server \; send-keys "/home/yukon/anaconda3/envs/pymesh/bin/python -m visdom.server -p 8890 > /dev/null 2>&1" Enter
sh: 1: tmux: not found
Launching new HTTP instance in port 8891
TMUX=0 tmux new-session -d -s http_server \; send-keys "/home/yukon/anaconda3/envs/pymesh/bin/python -m http.server -p 8891 > /dev/null 2>&1" Enter
sh: 1: tmux: not found
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/http/client.py", line 1291, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/http/client.py", line 1337, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/http/client.py", line 1286, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2834dcc2b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8890): Max retries exceeded with url: /env/Atlasnetatlasnet_singleview_1_sphere_2atlasnet_singleview_1_sphere (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2834dcc2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/visdom/__init__.py", line 695, in _send
    data=json.dumps(msg),
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/visdom/__init__.py", line 656, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8890): Max retries exceeded with url: /env/Atlasnetatlasnet_singleview_1_sphere_2atlasnet_singleview_1_sphere (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2834dcc2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[Errno 111] Connection refused
on_close() takes 1 positional argument but 3 were given
New MLP decoder : hidden size 512, num_layers 2, activation relu
Network weights loaded from  ./training/trained_models/atlasnet_singleview_1_sphere/network.pth!
Atlasnet generated mesh at ./doc/pictures/plane_input_demoAtlasnetReconstruction.ply!

Process finished with exit code 0

**Comment by ThibaultGROUEIX** [comment]
Hi @tang-y-q 

I see `sh: 1: tmux: not found`
I suggest to install tmux.

`sudo apt-get install tmux`

Best regards
Thibault

**Comment by tang-y-q** [comment]
> Hi @tang-y-q
> 
> I see `sh: 1: tmux: not found` I suggest to install tmux.
> 
> `sudo apt-get install tmux`
> 
> Best regards Thibault

Hi Thibault
Thank you very much for your reply. However, some problems occurred when I used your pretrained parameters for testing.
When I use the atlasnet_autoencoder_1_sphere trained_models, it can run normally. However, when I use atlasnet_autoencoder_25_squares  trained_models , an error is reported as follows:

THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=59 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "/home/yukon/AtlasNet-master/train.py", line 15, in <module>
    torch.cuda.set_device(opt.multi_gpu[0])
  File "/home/yukon/anaconda3/envs/pymesh/lib/python3.6/site-packages/torch/cuda/__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:59

I found many methods on the Internet, but none of them can solve this problem.It is said on the Internet that Pytorch will save the video card information when saving the model. When reloading, it will report an error if it finds that the video card is not the same.But I still can't solve this problem.
Could you please tell me how to modify the code to make it work properly？

 Best regards Yukon
